set(PACKAGE_VERSION "1.62.0.0")

if ("${PACKAGE_VERSION}" VERSION_EQUAL "${PACKAGE_FIND_VERSION}")
	set(PACKAGE_VERSION_COMPATIBLE TRUE)
	set(PACKAGE_VERSION_EXACT TRUE)
else()
	set(PACKAGE_VERSION_COMPATIBLE FALSE)
endif()
